version: '3'

services:
  db:
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rinha
      POSTGRES_DB: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rinha -d dev']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '300MB'

  api_with_pool:
    build: .
    hostname: api_with_pool
    restart: unless-stopped
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DATABASE_URL: postgres://rinha:password@db:5432/dev
      POOL_SIZE: 10
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '85MB'

  api_without_pool:
    build: .
    hostname: api_without_pool
    restart: unless-stopped
    ports:
      - '3001:3000'
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DATABASE_URL: postgres://rinha:password@db:5432/dev
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '85MB'